version: 1.0.{build}-{branch}

branches:
  only:
    - master
    - develop

skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\boiler'sGraphics

shallow_clone: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

configuration: Release

before_build:
  - ps: nuget restore boiler'sGraphics.sln

build:
  project: boiler'sGraphics.sln
  verbosity: minimal

after_build:
  - cmd: 7z a boiler_sGraphics.zip %APPVEYOR_BUILD_FOLDER%\boiler'sGraphics\bin\Release\*.*
  - cmd: 7z a boiler_sGraphics.zip %APPVEYOR_BUILD_FOLDER%\boiler'sGraphics\bin\Release\dll
  - cmd: 7z a boiler_sGraphics.zip %APPVEYOR_BUILD_FOLDER%\boiler'sGraphics\bin\Release\ja-JP

test:
  assemblies:
    only:
      - boiler_sGraphics.Test.dll

artifacts:
  - path: boiler_sGraphics.zip
    name: boiler_sGraphics.zip

deploy:
  - provider: GitHub
    artifact: boiler_sGraphics.zip
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#build'