using Reactive.Bindings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media;

namespace boilersGraphics.Models
{
    public class ColorSpots
    {
        public Color ColorSpot0 { get; set; } = Colors.White;
        public Color ColorSpot1 { get; set; } = Colors.White;
        public Color ColorSpot2 { get; set; } = Colors.White;
        public Color ColorSpot3 { get; set; } = Colors.White;
        public Color ColorSpot4 { get; set; } = Colors.White;
        public Color ColorSpot5 { get; set; } = Colors.White;
        public Color ColorSpot6 { get; set; } = Colors.White;
        public Color ColorSpot7 { get; set; } = Colors.White;
        public Color ColorSpot8 { get; set; } = Colors.White;
        public Color ColorSpot9 { get; set; } = Colors.White;
        public Color ColorSpot10 { get; set; } = Colors.White;
        public Color ColorSpot11 { get; set; } = Colors.White;
        public Color ColorSpot12 { get; set; } = Colors.White;
        public Color ColorSpot13 { get; set; } = Colors.White;
        public Color ColorSpot14 { get; set; } = Colors.White;
        public Color ColorSpot15 { get; set; } = Colors.White;
        public Color ColorSpot16 { get; set; } = Colors.White;
        public Color ColorSpot17 { get; set; } = Colors.White;
        public Color ColorSpot18 { get; set; } = Colors.White;
        public Color ColorSpot19 { get; set; } = Colors.White;
        public Color ColorSpot20 { get; set; } = Colors.White;
        public Color ColorSpot21 { get; set; } = Colors.White;
        public Color ColorSpot22 { get; set; } = Colors.White;
        public Color ColorSpot23 { get; set; } = Colors.White;
        public Color ColorSpot24 { get; set; } = Colors.White;
        public Color ColorSpot25 { get; set; } = Colors.White;
        public Color ColorSpot26 { get; set; } = Colors.White;
        public Color ColorSpot27 { get; set; } = Colors.White;
        public Color ColorSpot28 { get; set; } = Colors.White;
        public Color ColorSpot29 { get; set; } = Colors.White;
        public Color ColorSpot30 { get; set; } = Colors.White;
        public Color ColorSpot31 { get; set; } = Colors.White;
        public Color ColorSpot32 { get; set; } = Colors.White;
        public Color ColorSpot33 { get; set; } = Colors.White;
        public Color ColorSpot34 { get; set; } = Colors.White;
        public Color ColorSpot35 { get; set; } = Colors.White;
        public Color ColorSpot36 { get; set; } = Colors.White;
        public Color ColorSpot37 { get; set; } = Colors.White;
        public Color ColorSpot38 { get; set; } = Colors.White;
        public Color ColorSpot39 { get; set; } = Colors.White;
        public Color ColorSpot40 { get; set; } = Colors.White;
        public Color ColorSpot41 { get; set; } = Colors.White;
        public Color ColorSpot42 { get; set; } = Colors.White;
        public Color ColorSpot43 { get; set; } = Colors.White;
        public Color ColorSpot44 { get; set; } = Colors.White;
        public Color ColorSpot45 { get; set; } = Colors.White;
        public Color ColorSpot46 { get; set; } = Colors.White;
        public Color ColorSpot47 { get; set; } = Colors.White;
        public Color ColorSpot48 { get; set; } = Colors.White;
        public Color ColorSpot49 { get; set; } = Colors.White;
        public Color ColorSpot50 { get; set; } = Colors.White;
        public Color ColorSpot51 { get; set; } = Colors.White;
        public Color ColorSpot52 { get; set; } = Colors.White;
        public Color ColorSpot53 { get; set; } = Colors.White;
        public Color ColorSpot54 { get; set; } = Colors.White;
        public Color ColorSpot55 { get; set; } = Colors.White;
        public Color ColorSpot56 { get; set; } = Colors.White;
        public Color ColorSpot57 { get; set; } = Colors.White;
        public Color ColorSpot58 { get; set; } = Colors.White;
        public Color ColorSpot59 { get; set; } = Colors.White;
        public Color ColorSpot60 { get; set; } = Colors.White;
        public Color ColorSpot61 { get; set; } = Colors.White;
        public Color ColorSpot62 { get; set; } = Colors.White;
        public Color ColorSpot63 { get; set; } = Colors.White;
        public Color ColorSpot64 { get; set; } = Colors.White;
        public Color ColorSpot65 { get; set; } = Colors.White;
        public Color ColorSpot66 { get; set; } = Colors.White;
        public Color ColorSpot67 { get; set; } = Colors.White;
        public Color ColorSpot68 { get; set; } = Colors.White;
        public Color ColorSpot69 { get; set; } = Colors.White;
        public Color ColorSpot70 { get; set; } = Colors.White;
        public Color ColorSpot71 { get; set; } = Colors.White;
        public Color ColorSpot72 { get; set; } = Colors.White;
        public Color ColorSpot73 { get; set; } = Colors.White;
        public Color ColorSpot74 { get; set; } = Colors.White;
        public Color ColorSpot75 { get; set; } = Colors.White;
        public Color ColorSpot76 { get; set; } = Colors.White;
        public Color ColorSpot77 { get; set; } = Colors.White;
        public Color ColorSpot78 { get; set; } = Colors.White;
        public Color ColorSpot79 { get; set; } = Colors.White;
        public Color ColorSpot80 { get; set; } = Colors.White;
        public Color ColorSpot81 { get; set; } = Colors.White;
        public Color ColorSpot82 { get; set; } = Colors.White;
        public Color ColorSpot83 { get; set; } = Colors.White;
        public Color ColorSpot84 { get; set; } = Colors.White;
        public Color ColorSpot85 { get; set; } = Colors.White;
        public Color ColorSpot86 { get; set; } = Colors.White;
        public Color ColorSpot87 { get; set; } = Colors.White;
        public Color ColorSpot88 { get; set; } = Colors.White;
        public Color ColorSpot89 { get; set; } = Colors.White;
        public Color ColorSpot90 { get; set; } = Colors.White;
        public Color ColorSpot91 { get; set; } = Colors.White;
        public Color ColorSpot92 { get; set; } = Colors.White;
        public Color ColorSpot93 { get; set; } = Colors.White;
        public Color ColorSpot94 { get; set; } = Colors.White;
        public Color ColorSpot95 { get; set; } = Colors.White;
        public Color ColorSpot96 { get; set; } = Colors.White;
        public Color ColorSpot97 { get; set; } = Colors.White;
        public Color ColorSpot98 { get; set; } = Colors.White;
        public Color ColorSpot99 { get; set; } = Colors.White;
    }
}
