using Reactive.Bindings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media;

namespace boilersGraphics.Models
{
    public class ColorSpots
    {
        public Brush ColorSpot0 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot1 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot2 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot3 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot4 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot5 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot6 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot7 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot8 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot9 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot10 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot11 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot12 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot13 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot14 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot15 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot16 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot17 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot18 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot19 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot20 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot21 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot22 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot23 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot24 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot25 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot26 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot27 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot28 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot29 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot30 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot31 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot32 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot33 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot34 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot35 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot36 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot37 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot38 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot39 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot40 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot41 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot42 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot43 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot44 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot45 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot46 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot47 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot48 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot49 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot50 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot51 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot52 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot53 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot54 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot55 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot56 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot57 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot58 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot59 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot60 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot61 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot62 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot63 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot64 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot65 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot66 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot67 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot68 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot69 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot70 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot71 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot72 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot73 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot74 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot75 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot76 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot77 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot78 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot79 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot80 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot81 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot82 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot83 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot84 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot85 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot86 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot87 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot88 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot89 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot90 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot91 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot92 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot93 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot94 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot95 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot96 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot97 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot98 { get; set; } = new SolidColorBrush(Colors.White);
        public Brush ColorSpot99 { get; set; } = new SolidColorBrush(Colors.White);
    }
}
