//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace boilersGraphics.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boilersGraphics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_MaximizeWindow {
            get {
                return ResourceManager.GetString("Button_MaximizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_MinimizeWindow {
            get {
                return ResourceManager.GetString("Button_MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Restore {
            get {
                return ResourceManager.GetString("Button_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignBottom {
            get {
                return ResourceManager.GetString("Command_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align horizontal center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignHorizontalCenter {
            get {
                return ResourceManager.GetString("Command_AlignHorizontalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignLeft {
            get {
                return ResourceManager.GetString("Command_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignRight {
            get {
                return ResourceManager.GetString("Command_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignTop {
            get {
                return ResourceManager.GetString("Command_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align vertical center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignVerticalCenter {
            get {
                return ResourceManager.GetString("Command_AlignVerticalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bring foreground に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_BringForeground {
            get {
                return ResourceManager.GetString("Command_BringForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bring forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_BringForward {
            get {
                return ResourceManager.GetString("Command_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distribute horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DistributeHorizontal {
            get {
                return ResourceManager.GetString("Command_DistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distribute vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DistributeVertical {
            get {
                return ResourceManager.GetString("Command_DistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Export {
            get {
                return ResourceManager.GetString("Command_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Group {
            get {
                return ResourceManager.GetString("Command_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Load {
            get {
                return ResourceManager.GetString("Command_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Overwrite {
            get {
                return ResourceManager.GetString("Command_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SendBackground {
            get {
                return ResourceManager.GetString("Command_SendBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send backward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SendBackward {
            get {
                return ResourceManager.GetString("Command_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Setting {
            get {
                return ResourceManager.GetString("Command_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ungroup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Ungroup {
            get {
                return ResourceManager.GetString("Command_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uniform height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UniformHeight {
            get {
                return ResourceManager.GetString("Command_UniformHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uniform width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UniformWidth {
            get {
                return ResourceManager.GetString("Command_UniformWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brush thickness に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_BrushThickness {
            get {
                return ResourceManager.GetString("MenuItem_BrushThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canvas(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Canvas {
            get {
                return ResourceManager.GetString("MenuItem_Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set clip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Clip {
            get {
                return ResourceManager.GetString("MenuItem_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Cut {
            get {
                return ResourceManager.GetString("MenuItem_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Edit {
            get {
                return ResourceManager.GetString("MenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English(US) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_en_US {
            get {
                return ResourceManager.GetString("MenuItem_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit boiler&apos;s Graphics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExitApplication {
            get {
                return ResourceManager.GetString("MenuItem_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Export {
            get {
                return ResourceManager.GetString("MenuItem_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ja_JP {
            get {
                return ResourceManager.GetString("MenuItem_ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Language {
            get {
                return ResourceManager.GetString("MenuItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Log {
            get {
                return ResourceManager.GetString("MenuItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Debug {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Error {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fatal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Fatal {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Info {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Off {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Trace {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_LogLevel_Warn {
            get {
                return ResourceManager.GetString("MenuItem_LogLevel_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mini map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_MiniMap {
            get {
                return ResourceManager.GetString("MenuItem_MiniMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Open {
            get {
                return ResourceManager.GetString("MenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Overwrite {
            get {
                return ResourceManager.GetString("MenuItem_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Paste {
            get {
                return ResourceManager.GetString("MenuItem_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preference(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Preference {
            get {
                return ResourceManager.GetString("MenuItem_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Property {
            get {
                return ResourceManager.GetString("MenuItem_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Redo {
            get {
                return ResourceManager.GetString("MenuItem_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_SaveAs {
            get {
                return ResourceManager.GetString("MenuItem_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open application log(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ShowLog {
            get {
                return ResourceManager.GetString("MenuItem_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify File(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_SpecifyFile {
            get {
                return ResourceManager.GetString("MenuItem_SpecifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the automatically saved file(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_SpecifyFileAutoSaved {
            get {
                return ResourceManager.GetString("MenuItem_SpecifyFileAutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Statistics(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Statistics {
            get {
                return ResourceManager.GetString("MenuItem_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Undo {
            get {
                return ResourceManager.GetString("MenuItem_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version information of boiler&apos;s Graphics(_I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Version {
            get {
                return ResourceManager.GetString("MenuItem_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Window {
            get {
                return ResourceManager.GetString("MenuItem_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ordering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_A {
            get {
                return ResourceManager.GetString("String_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_B {
            get {
                return ResourceManager.GetString("String_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Cancel {
            get {
                return ResourceManager.GetString("String_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Export {
            get {
                return ResourceManager.GetString("String_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_FileName {
            get {
                return ResourceManager.GetString("String_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_G {
            get {
                return ResourceManager.GetString("String_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Hue {
            get {
                return ResourceManager.GetString("String_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quality level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_QualityLevel {
            get {
                return ResourceManager.GetString("String_QualityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_R {
            get {
                return ResourceManager.GetString("String_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String_Reference {
            get {
                return ResourceManager.GetString("String_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color picker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ColorPicker {
            get {
                return ResourceManager.GetString("Title_ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Export {
            get {
                return ResourceManager.GetString("Title_Export", resourceCulture);
            }
        }
    }
}
