//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace boilersGraphics.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("boilersGraphics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alignment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignBottom {
            get {
                return ResourceManager.GetString("Command_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align horizontal center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignHorizontalCenter {
            get {
                return ResourceManager.GetString("Command_AlignHorizontalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignLeft {
            get {
                return ResourceManager.GetString("Command_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignRight {
            get {
                return ResourceManager.GetString("Command_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignTop {
            get {
                return ResourceManager.GetString("Command_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Align vertical center に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_AlignVerticalCenter {
            get {
                return ResourceManager.GetString("Command_AlignVerticalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bring foreground に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_BringForeground {
            get {
                return ResourceManager.GetString("Command_BringForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bring forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_BringForward {
            get {
                return ResourceManager.GetString("Command_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distribute horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DistributeHorizontal {
            get {
                return ResourceManager.GetString("Command_DistributeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distribute vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DistributeVertical {
            get {
                return ResourceManager.GetString("Command_DistributeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Export {
            get {
                return ResourceManager.GetString("Command_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Group {
            get {
                return ResourceManager.GetString("Command_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SendBackground {
            get {
                return ResourceManager.GetString("Command_SendBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send backward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_SendBackward {
            get {
                return ResourceManager.GetString("Command_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Setting {
            get {
                return ResourceManager.GetString("Command_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ungroup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Ungroup {
            get {
                return ResourceManager.GetString("Command_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uniform height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UniformHeight {
            get {
                return ResourceManager.GetString("Command_UniformHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uniform width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_UniformWidth {
            get {
                return ResourceManager.GetString("Command_UniformWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grouping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ordering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
    }
}
