using boilersGraphics.Models.Animation;
using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Windows.Media;

namespace boilersGraphics.Helpers.Animation.Export;

/// <summary>
/// Phase 5.5-d-5: MAUI <c>ContentView</c> 用の code-behind (<c>.xaml.cs</c>) を組み立てる pure builder。
///
/// 仕様書 §3.2 / Q-4 案 C: Loaded で自動起動 + 公開 <c>BeginAnimation()</c> / <c>StopAnimation()</c>。
/// Track ごとに parent <c>Animation</c> を作り、Keyframe ペアごとに child <c>Animation</c> を
/// <c>parent.Add(beginAt, finishAt, child)</c> で時間配置する。<c>length</c> は Timeline.Duration の ms。
/// </summary>
public static class MauiAnimationCodeBehindBuilder
{
    private const string GeneratorComment = "// Generated by boilersGraphics Phase 5.5 v1.0";

    /// <summary>
    /// code-behind C# 文字列を返す。
    /// </summary>
    public static string Build(
        TimelineViewModel timeline,
        XamlExportSettings settings,
        IReadOnlyDictionary<Guid, string> itemTagOverrides = null)
    {
        if (timeline is null) throw new ArgumentNullException(nameof(timeline));
        if (settings is null) throw new ArgumentNullException(nameof(settings));

        var nl = settings.NewLine;
        var ind = new string(' ', settings.IndentWidth);
        var ind2 = new string(' ', settings.IndentWidth * 2);

        var usedColor = false;
        var bounceNeeded = false;

        // length ms; 0 のときは 1 秒に切り上げる (Commit に length=0 を渡すと例外)
        var durationSec = timeline.Duration.Value > 0 ? timeline.Duration.Value : 1.0;
        var lengthMs = (uint)Math.Max(1, Math.Round(durationSec * 1000));
        var loop = timeline.Loop.Value;

        var trackBlocks = new StringBuilder();
        var stopBlocks = new StringBuilder();

        foreach (var (track, trackIdx) in timeline.Tracks.Select((t, i) => (t, i)))
        {
            var mapping = MauiPropertyToCSharpMapper.TryMap(track.Target.PropertyPath);
            if (mapping is null)
            {
                trackBlocks.Append(ind2).Append("// Skipped: unsupported PropertyPath '").Append(track.Target.PropertyPath).Append('\'').Append(nl);
                continue;
            }

            if (track.Keyframes.Count < 2)
            {
                trackBlocks.Append(ind2).Append("// Skipped Track ").Append(trackIdx).Append(": fewer than 2 keyframes").Append(nl);
                continue;
            }

            var targetName = ShapeToXamlMapper.MakeXName(track.Target.ItemId);
            var pathBase = SanitizePropertyName(track.Target.PropertyPath);
            var parentVar = $"__parent_{trackIdx}_{pathBase}";
            var commitName = $"{targetName}_{pathBase}_anim_{trackIdx}";

            trackBlocks.Append(ind2).Append("// Track ").Append(trackIdx).Append(" :: ").Append(targetName).Append('.').Append(pathBase).Append(nl);
            trackBlocks.Append(ind2).Append("var ").Append(parentVar).Append(" = new Animation();").Append(nl);

            var ordered = track.Keyframes.OrderBy(k => k.Time.Value).ToList();
            for (var i = 0; i < ordered.Count - 1; i++)
            {
                var k0 = ordered[i];
                var k1 = ordered[i + 1];
                var beginAt = ClampFraction(k0.Time.Value / durationSec);
                var finishAt = ClampFraction(k1.Time.Value / durationSec);
                if (finishAt <= beginAt) continue;

                var easingExpr = MauiEasingToCSharpMapper.ToExpression(k0.Easing.Value, k0.Mode.Value);
                if (MauiEasingToCSharpMapper.RequiresBounceHelper(k0.Easing.Value, k0.Mode.Value)) bounceNeeded = true;

                if (mapping.Kind == MauiAnimationKind.Double)
                {
                    var fromValue = ToInvariant(k0.Value.Value);
                    var toValue = ToInvariant(k1.Value.Value);
                    var body = string.Format(CultureInfo.InvariantCulture, mapping.DoubleCallbackTemplate, targetName);
                    trackBlocks.Append(ind2).Append(parentVar).Append(".Add(")
                        .Append(FormatFraction(beginAt)).Append(", ").Append(FormatFraction(finishAt))
                        .Append(", new Animation(d => { ").Append(body).Append(" }, ")
                        .Append(fromValue).Append(", ").Append(toValue).Append(", ").Append(easingExpr).Append("));").Append(nl);
                }
                else
                {
                    usedColor = true;
                    var fromColor = FormatColorArg(k0.Value.Value);
                    var toColor = FormatColorArg(k1.Value.Value);
                    var body = string.Format(CultureInfo.InvariantCulture, mapping.ColorCallbackTemplate, targetName);
                    trackBlocks.Append(ind2).Append(parentVar).Append(".Add(")
                        .Append(FormatFraction(beginAt)).Append(", ").Append(FormatFraction(finishAt))
                        .Append(", new Animation(d => { var c = LerpColor(")
                        .Append(fromColor).Append(", ").Append(toColor).Append(", d); ").Append(body).Append(" }, 0, 1, ")
                        .Append(easingExpr).Append("));").Append(nl);
                }
            }

            trackBlocks.Append(ind2).Append(parentVar).Append(".Commit(this, \"").Append(commitName)
                .Append("\", length: ").Append(lengthMs).Append("u, easing: Easing.Linear, repeat: () => ").Append(loop ? "true" : "false").Append(");").Append(nl);
            trackBlocks.Append(nl);

            stopBlocks.Append(ind2).Append("this.AbortAnimation(\"").Append(commitName).Append("\");").Append(nl);
        }

        var sb = new StringBuilder();
        if (settings.IncludeHeaderComment) sb.Append(GeneratorComment).Append(nl);
        sb.Append("using System;").Append(nl);
        sb.Append("using Microsoft.Maui.Controls;").Append(nl);
        sb.Append("using Microsoft.Maui.Controls.Shapes;").Append(nl);
        sb.Append("using Microsoft.Maui.Graphics;").Append(nl);
        sb.Append(nl);
        sb.Append("namespace ").Append(settings.TargetNamespace).Append(';').Append(nl);
        sb.Append(nl);
        sb.Append(settings.AccessModifier).Append(" partial class ").Append(settings.ClassName).Append(" : ContentView").Append(nl);
        sb.Append('{').Append(nl);
        sb.Append(ind).Append("public ").Append(settings.ClassName).Append("()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(ind2).Append("InitializeComponent();").Append(nl);
        sb.Append(ind2).Append("Loaded += (s, e) => BeginAnimation();").Append(nl);
        sb.Append(ind).Append('}').Append(nl);
        sb.Append(nl);
        sb.Append(ind).Append("public void BeginAnimation()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(ind2).Append("StopAnimation();").Append(nl);
        sb.Append(trackBlocks);
        sb.Append(ind).Append('}').Append(nl);
        sb.Append(nl);
        sb.Append(ind).Append("public void StopAnimation()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(stopBlocks);
        sb.Append(ind).Append('}').Append(nl);

        if (usedColor)
        {
            sb.Append(nl);
            sb.Append(ind).Append("private static Color LerpColor(Color from, Color to, double d)").Append(nl);
            sb.Append(ind).Append('{').Append(nl);
            sb.Append(ind2).Append("return Color.FromRgba(").Append(nl);
            sb.Append(ind2).Append(ind).Append("from.Red + (to.Red - from.Red) * d,").Append(nl);
            sb.Append(ind2).Append(ind).Append("from.Green + (to.Green - from.Green) * d,").Append(nl);
            sb.Append(ind2).Append(ind).Append("from.Blue + (to.Blue - from.Blue) * d,").Append(nl);
            sb.Append(ind2).Append(ind).Append("from.Alpha + (to.Alpha - from.Alpha) * d);").Append(nl);
            sb.Append(ind).Append('}').Append(nl);
        }

        if (bounceNeeded)
        {
            sb.Append(nl);
            foreach (var line in MauiEasingToCSharpMapper.BounceHelperSource.Split('\n'))
            {
                sb.Append(ind).Append(line.TrimEnd('\r')).Append(nl);
            }
        }

        sb.Append('}').Append(nl);
        return sb.ToString();
    }

    private static string SanitizePropertyName(string propertyPath)
    {
        if (string.IsNullOrEmpty(propertyPath)) return "Prop";
        var dot = propertyPath.IndexOf('.');
        var head = dot > 0 ? propertyPath.Substring(0, dot) : propertyPath;
        var sb = new StringBuilder();
        foreach (var ch in head)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_') sb.Append(ch);
        }
        return sb.Length == 0 ? "Prop" : sb.ToString();
    }

    private static double ClampFraction(double f) => f < 0 ? 0 : (f > 1 ? 1 : f);

    private static string FormatFraction(double f) => f.ToString("0.######", CultureInfo.InvariantCulture);

    private static string ToInvariant(object value) => value switch
    {
        double d => d.ToString("0.######", CultureInfo.InvariantCulture),
        float f => f.ToString("0.######", CultureInfo.InvariantCulture),
        int i => i.ToString(CultureInfo.InvariantCulture),
        long l => l.ToString(CultureInfo.InvariantCulture),
        _ => "0",
    };

    /// <summary>
    /// Color / Brush 値を <c>Color.FromArgb("#AARRGGBB")</c> 形式の C# 式に変換。
    /// </summary>
    private static string FormatColorArg(object value)
    {
        var hex = value switch
        {
            Color c => c.ToString(CultureInfo.InvariantCulture),
            SolidColorBrush scb => scb.Color.ToString(CultureInfo.InvariantCulture),
            Brush b => b.ToString(CultureInfo.InvariantCulture),
            _ => "#00000000",
        };
        return "Color.FromArgb(\"" + hex + "\")";
    }
}
