using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Media;

namespace boilersGraphics.Helpers.Animation.Export;

/// <summary>
/// Phase 5.5-d-4: MAUI <c>ContentView</c> + <c>AbsoluteLayout</c> + 各図形 XAML を組み立てる pure builder。
/// アニメ本体はコード側 (Phase 5.5-d-5 の <see cref="MauiAnimationCodeBehindBuilder"/>) で吐く。
/// </summary>
public static class MauiAnimationXamlBuilder
{
    private const string GeneratorComment = "<!-- Generated by boilersGraphics Phase 5.5 v1.0 -->";

    /// <summary>
    /// ContentView XAML 全体 (Resources/Triggers なし、AbsoluteLayout に図形を並べるだけ) を返す。
    /// </summary>
    public static string Build(
        TimelineViewModel timeline,
        IReadOnlyList<SelectableDesignerItemViewModelBase> allItems,
        XamlExportSettings settings,
        Func<SelectableDesignerItemViewModelBase, PathGeometry> pathGeometryResolver = null)
    {
        if (timeline is null) throw new ArgumentNullException(nameof(timeline));
        if (allItems is null) throw new ArgumentNullException(nameof(allItems));
        if (settings is null) throw new ArgumentNullException(nameof(settings));

        var nl = settings.NewLine;
        var ind1 = new string(' ', settings.IndentWidth);
        var ind2 = new string(' ', settings.IndentWidth * 2);

        var sb = new StringBuilder();
        if (settings.IncludeHeaderComment) sb.Append(GeneratorComment).Append(nl);

        sb.Append("<ContentView x:Class=\"").Append(settings.TargetNamespace).Append('.').Append(settings.ClassName).Append('"').Append(nl);
        sb.Append("             xmlns=\"http://schemas.microsoft.com/dotnet/2021/maui\"").Append(nl);
        sb.Append("             xmlns:x=\"http://schemas.microsoft.com/winfx/2009/xaml\">").Append(nl);

        sb.Append(ind1).Append("<ContentView.Content>").Append(nl);
        sb.Append(ind2).Append("<AbsoluteLayout>").Append(nl);
        AppendShapes(sb, allItems, settings, pathGeometryResolver, indentLevel: 3);
        sb.Append(ind2).Append("</AbsoluteLayout>").Append(nl);
        sb.Append(ind1).Append("</ContentView.Content>").Append(nl);
        sb.Append("</ContentView>").Append(nl);
        return sb.ToString();
    }

    private static void AppendShapes(StringBuilder sb, IReadOnlyList<SelectableDesignerItemViewModelBase> allItems, XamlExportSettings settings, Func<SelectableDesignerItemViewModelBase, PathGeometry> resolver, int indentLevel)
    {
        var nl = settings.NewLine;
        var indent = new string(' ', settings.IndentWidth * indentLevel);
        foreach (var item in allItems)
        {
            var xaml = MauiShapeToXamlMapper.TryMapMauiShape(item, settings, indentLevel);
            if (xaml is not null) { sb.Append(xaml).Append(nl); continue; }
            var geom = resolver?.Invoke(item);
            xaml = MauiShapeToXamlMapper.TryMapMauiPath(item, geom, settings, indentLevel);
            if (xaml is not null) { sb.Append(xaml).Append(nl); continue; }
            sb.Append(indent).Append("<!-- Skipped unsupported item: ").Append(item.GetType().Name).Append(" (").Append(item.ID.ToString("N")).Append(") -->").Append(nl);
        }
    }
}
