using boilersGraphics.Models.Animation;
using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Windows.Media;

namespace boilersGraphics.Helpers.Animation.Export;

/// <summary>
/// Phase 5.5-b-5: Phase 5 の IR (<see cref="TimelineViewModel"/>) と Canvas 上の図形群を
/// WPF <c>UserControl</c> + <c>Storyboard</c> の XAML 文字列に変換する pure builder。
///
/// 入力すべて pure (副作用なし、ファイル IO なし)。Path 系図形 (Path/Polygon/Connector) は
/// <paramref name="pathGeometryResolver"/> 経由で外部から PathGeometry を解決させる。
/// 仕様書: <c>docs/fui/phase5-5-xaml-export.md</c> §3.1, §4.2, §10.1。
/// </summary>
public static class WpfStoryboardXamlBuilder
{
    private const string GeneratorComment = "<!-- Generated by boilersGraphics Phase 5.5 v1.0 -->";

    /// <summary>
    /// UserControl XAML 文字列を返す。
    /// </summary>
    /// <param name="timeline">Phase 5 IR。Tracks + Loop + Duration を読み取る。</param>
    /// <param name="allItems">Canvas 上の全 ViewModel。Tracks の <see cref="PropertyRef.ItemId"/> で解決される。</param>
    /// <param name="settings">名前空間 / クラス名 / インデント等。</param>
    /// <param name="pathGeometryResolver">
    /// Path 系図形に対して PathGeometry を返す関数 (Phase 5.5-c で実装)。
    /// null の場合、Path 系図形はコメントで省略される。
    /// </param>
    public static string Build(
        TimelineViewModel timeline,
        IReadOnlyList<SelectableDesignerItemViewModelBase> allItems,
        XamlExportSettings settings,
        Func<SelectableDesignerItemViewModelBase, PathGeometry> pathGeometryResolver = null)
    {
        if (timeline is null) throw new ArgumentNullException(nameof(timeline));
        if (allItems is null) throw new ArgumentNullException(nameof(allItems));
        if (settings is null) throw new ArgumentNullException(nameof(settings));

        var nl = settings.NewLine;
        var ind1 = new string(' ', settings.IndentWidth);
        var ind2 = new string(' ', settings.IndentWidth * 2);
        var ind3 = new string(' ', settings.IndentWidth * 3);
        var ind4 = new string(' ', settings.IndentWidth * 4);

        var sb = new StringBuilder();

        if (settings.IncludeHeaderComment)
        {
            sb.Append(GeneratorComment).Append(nl);
        }

        sb.Append("<UserControl x:Class=\"").Append(settings.TargetNamespace).Append('.').Append(settings.ClassName).Append('"').Append(nl);
        sb.Append("             xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"").Append(nl);
        sb.Append("             xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">").Append(nl);

        // ---------- Resources / Storyboard ----------
        sb.Append(ind1).Append("<UserControl.Resources>").Append(nl);
        AppendStoryboard(sb, timeline, ind2, ind3, ind4, settings);
        sb.Append(ind1).Append("</UserControl.Resources>").Append(nl);

        // ---------- Triggers (Loaded -> BeginStoryboard) ----------
        sb.Append(ind1).Append("<UserControl.Triggers>").Append(nl);
        sb.Append(ind2).Append("<EventTrigger RoutedEvent=\"UserControl.Loaded\">").Append(nl);
        sb.Append(ind3).Append("<BeginStoryboard Storyboard=\"{StaticResource MainStoryboard}\" />").Append(nl);
        sb.Append(ind2).Append("</EventTrigger>").Append(nl);
        sb.Append(ind1).Append("</UserControl.Triggers>").Append(nl);

        // ---------- Canvas + 図形 ----------
        sb.Append(ind1).Append("<Canvas>").Append(nl);
        AppendShapes(sb, allItems, settings, pathGeometryResolver, indentLevel: 2);
        sb.Append(ind1).Append("</Canvas>").Append(nl);

        sb.Append("</UserControl>").Append(nl);
        return sb.ToString();
    }

    private static void AppendStoryboard(StringBuilder sb, TimelineViewModel timeline, string ind2, string ind3, string ind4, XamlExportSettings settings)
    {
        var nl = settings.NewLine;
        var ind5 = new string(' ', settings.IndentWidth * 5);
        var ind6 = new string(' ', settings.IndentWidth * 6);

        sb.Append(ind2).Append("<Storyboard x:Key=\"MainStoryboard\"");
        if (timeline.Loop.Value) sb.Append(" RepeatBehavior=\"Forever\"");
        sb.Append('>').Append(nl);

        foreach (var track in timeline.Tracks)
        {
            var mapping = PropertyToXamlMapper.TryMapWpf(track.Target.PropertyPath);
            if (mapping is null)
            {
                sb.Append(ind3).Append("<!-- Skipped: unsupported PropertyPath '").Append(track.Target.PropertyPath).Append("' -->").Append(nl);
                continue;
            }

            var targetName = ShapeToXamlMapper.MakeXName(track.Target.ItemId);
            sb.Append(ind3).Append('<').Append(mapping.AnimationElementName)
              .Append(" Storyboard.TargetName=\"").Append(targetName).Append('"')
              .Append(" Storyboard.TargetProperty=\"").Append(mapping.TargetProperty).Append("\">").Append(nl);

            // Keyframes を時間順に書き出す
            var ordered = track.Keyframes.OrderBy(k => k.Time.Value).ToList();
            foreach (var kf in ordered)
            {
                AppendKeyframe(sb, kf, mapping, track.Target.ValueType, ind4, ind5, ind6, nl);
            }

            sb.Append(ind3).Append("</").Append(mapping.AnimationElementName).Append('>').Append(nl);
        }

        sb.Append(ind2).Append("</Storyboard>").Append(nl);
    }

    private static void AppendKeyframe(StringBuilder sb, Keyframe kf, PropertyToXamlMapper.WpfMapping mapping, AnimatedValueType valueType, string ind4, string ind5, string ind6, string nl)
    {
        var keyTime = FormatKeyTime(kf.Time.Value);
        var value = FormatKeyframeValue(kf.Value.Value, valueType);
        var requiresEasing = EasingToXamlMapper.RequiresEasingFunction(kf.Easing.Value);
        var element = requiresEasing ? mapping.EasingKeyFrameElementName : mapping.LinearKeyFrameElementName;

        if (!requiresEasing)
        {
            // <LinearDoubleKeyFrame KeyTime="..." Value="..." />
            sb.Append(ind4).Append('<').Append(element).Append(" KeyTime=\"").Append(keyTime).Append("\" Value=\"").Append(value).Append("\" />").Append(nl);
            return;
        }

        // <EasingDoubleKeyFrame KeyTime="..." Value="...">
        //     <EasingDoubleKeyFrame.EasingFunction>
        //         <SineEase EasingMode="EaseInOut" />
        //     </EasingDoubleKeyFrame.EasingFunction>
        // </EasingDoubleKeyFrame>
        sb.Append(ind4).Append('<').Append(element).Append(" KeyTime=\"").Append(keyTime).Append("\" Value=\"").Append(value).Append("\">").Append(nl);
        sb.Append(ind5).Append('<').Append(element).Append(".EasingFunction>").Append(nl);
        var easingXaml = EasingToXamlMapper.ToWpfEasingXaml(kf.Easing.Value, kf.Mode.Value);
        sb.Append(ind6).Append(easingXaml).Append(nl);
        sb.Append(ind5).Append("</").Append(element).Append(".EasingFunction>").Append(nl);
        sb.Append(ind4).Append("</").Append(element).Append('>').Append(nl);
    }

    private static void AppendShapes(StringBuilder sb, IReadOnlyList<SelectableDesignerItemViewModelBase> allItems, XamlExportSettings settings, Func<SelectableDesignerItemViewModelBase, PathGeometry> pathGeometryResolver, int indentLevel)
    {
        var nl = settings.NewLine;
        var indent = new string(' ', settings.IndentWidth * indentLevel);

        foreach (var item in allItems)
        {
            var xaml = ShapeToXamlMapper.TryMapWpfShape(item, settings, indentLevel);
            if (xaml is not null)
            {
                sb.Append(xaml).Append(nl);
                continue;
            }

            // Path 系のリゾルバ経由
            var geom = pathGeometryResolver?.Invoke(item);
            xaml = ShapeToXamlMapper.TryMapWpfPath(item, geom, settings, indentLevel);
            if (xaml is not null)
            {
                sb.Append(xaml).Append(nl);
                continue;
            }

            // 未対応図形 (テキスト系等) はコメントで明示
            sb.Append(indent).Append("<!-- Skipped unsupported item: ").Append(item.GetType().Name).Append(" (").Append(item.ID.ToString("N")).Append(") -->").Append(nl);
        }
    }

    /// <summary>
    /// 秒単位 (double) を WPF KeyTime "h:m:s" 形式に変換。秒は小数 6 桁まで保持。
    /// </summary>
    public static string FormatKeyTime(double seconds)
    {
        if (seconds < 0) seconds = 0;
        var total = TimeSpan.FromSeconds(seconds);
        var h = total.Hours;
        var m = total.Minutes;
        var s = seconds - h * 3600.0 - m * 60.0;
        return string.Format(CultureInfo.InvariantCulture, "{0}:{1}:{2:0.######}", h, m, s);
    }

    /// <summary>
    /// Keyframe.Value を XAML 属性用の文字列に変換。
    /// Color / SolidColorBrush は #AARRGGBB、double / int は invariant culture、それ以外は ToString フォールバック。
    /// </summary>
    public static string FormatKeyframeValue(object value, AnimatedValueType valueType)
    {
        if (value is null) return string.Empty;
        return value switch
        {
            Color c => c.ToString(CultureInfo.InvariantCulture),
            SolidColorBrush scb => scb.Color.ToString(CultureInfo.InvariantCulture),
            Brush b => b.ToString(CultureInfo.InvariantCulture),
            double d => d.ToString("0.######", CultureInfo.InvariantCulture),
            float f => f.ToString("0.######", CultureInfo.InvariantCulture),
            int i => i.ToString(CultureInfo.InvariantCulture),
            bool bo => bo ? "True" : "False",
            IFormattable fmt => fmt.ToString(null, CultureInfo.InvariantCulture),
            _ => value.ToString() ?? string.Empty,
        };
    }
}
