using System.Text;

namespace boilersGraphics.Helpers.Animation.Export;

/// <summary>
/// Phase 5.5-c: <see cref="WpfStoryboardXamlBuilder"/> が出す <c>x:Class</c> 付き UserControl XAML に
/// 対応する code-behind (<c>.xaml.cs</c>) を生成する pure helper。
///
/// 仕様書 Q-4 案 C: Loaded 自動起動 + 公開メソッド <c>BeginAnimation()</c> / <c>StopAnimation()</c> を出す。
/// </summary>
public static class WpfStoryboardCodeBehindBuilder
{
    /// <summary>
    /// XamlExportSettings の TargetNamespace / ClassName / AccessModifier / NewLine / IndentWidth を
    /// 反映した C# code-behind 文字列を返す。
    /// </summary>
    public static string Build(XamlExportSettings settings)
    {
        if (settings is null) return string.Empty;
        var nl = settings.NewLine;
        var ind = new string(' ', settings.IndentWidth);
        var ind2 = new string(' ', settings.IndentWidth * 2);
        var ns = settings.TargetNamespace;
        var cls = settings.ClassName;
        var access = settings.AccessModifier;

        var sb = new StringBuilder();
        if (settings.IncludeHeaderComment)
        {
            sb.Append("// Generated by boilersGraphics Phase 5.5 v1.0").Append(nl);
        }
        sb.Append("using System.Windows.Controls;").Append(nl);
        sb.Append("using System.Windows.Media.Animation;").Append(nl);
        sb.Append(nl);
        sb.Append("namespace ").Append(ns).Append(';').Append(nl);
        sb.Append(nl);
        sb.Append(access).Append(" partial class ").Append(cls).Append(" : UserControl").Append(nl);
        sb.Append('{').Append(nl);
        sb.Append(ind).Append("public ").Append(cls).Append("()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(ind2).Append("InitializeComponent();").Append(nl);
        sb.Append(ind).Append('}').Append(nl);
        sb.Append(nl);
        sb.Append(ind).Append("public void BeginAnimation()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(ind2).Append("var sb = (Storyboard)FindResource(\"MainStoryboard\");").Append(nl);
        sb.Append(ind2).Append("sb.Begin(this, true);").Append(nl);
        sb.Append(ind).Append('}').Append(nl);
        sb.Append(nl);
        sb.Append(ind).Append("public void StopAnimation()").Append(nl);
        sb.Append(ind).Append('{').Append(nl);
        sb.Append(ind2).Append("var sb = (Storyboard)FindResource(\"MainStoryboard\");").Append(nl);
        sb.Append(ind2).Append("sb.Stop(this);").Append(nl);
        sb.Append(ind).Append('}').Append(nl);
        sb.Append('}').Append(nl);
        return sb.ToString();
    }
}
