namespace boilersGraphics.Helpers.Animation.Export;

/// <summary>
/// Phase 5.5-b: XAML 出力の整形 / 名前空間 / クラス名などの設定 DTO。
/// 全項目に既定値があり、ユーザーが上書きしたい項目のみ <c>with</c> で差し替える前提。
///
/// 仕様書: <c>docs/fui/phase5-5-xaml-export.md</c> §10.2
/// </summary>
public sealed record class XamlExportSettings
{
    public string TargetNamespace { get; init; } = "MyApp.Animations";
    public string ClassName { get; init; } = "FuiAnimation";

    /// <summary>"public" / "internal" のいずれか。</summary>
    public string AccessModifier { get; init; } = "public";

    /// <summary>true なら <c>.xaml.cs</c> も生成 (Q-4 案 C)。Phase 5.5-b 時点では Builder の string 出力には影響しないが、Exporter (5.5-c) が参照する。</summary>
    public bool GenerateCodeBehind { get; init; } = true;

    /// <summary>インデント幅 (半角スペース数)。2 / 4 を想定。</summary>
    public int IndentWidth { get; init; } = 4;

    /// <summary>改行コード。既定は CRLF (Windows)。LF 強制も可。</summary>
    public string NewLine { get; init; } = "\r\n";

    /// <summary>ファイル冒頭の <c>&lt;!-- Generated by boilersGraphics ... --&gt;</c> コメントを出すかどうか。</summary>
    public bool IncludeHeaderComment { get; init; } = true;
}
