# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'
  System.Debug: True
  TargetSolution: '$(Build.SourcesDirectory)\boilersGraphics.sln'
  TestProjects: '$(Build.SourcesDirectory)\boilersGraphics.Test\*.Test.csproj'

steps:
- task: NuGetToolInstaller@1

- powershell: |
   $Version = git describe --tags --abbrev=0
   $Version -match '^v(?<major>\d+?)\.(?<minor>\d+?)\.?(?<build>\d*?)$'
   $Major = $Matches['major']
   $Minor = $Matches['minor']
   Write-Host "##vso[task.setvariable variable=Major]$Major"
   Write-Host "##vso[task.setvariable variable=Minor]$Minor"
   if ($Matches.ContainsKey("build") -and $Matches['build'] -ne '')
   {
       $Build = $Matches['build']
       Write-Host "##vso[task.setvariable variable=Build]$Build"
   } else {
       $Build = 0
   }
  displayName: 'Get version'

- task: DotNetCoreCLI@2
  displayName: 'NuGet パッケージの復元'
  inputs:
    command: 'restore'
    projects: '$(TargetSolution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'アプリケーションのビルド'
  inputs:
    command: 'build'
    projects: '$(TargetSolution)'
    arguments: '--configuration $(BuildConfiguration)'  

- powershell: |
       [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq") | Out-Null
       $path = (Convert-Path .) + "/boilersGraphics.Msix/Package.appxmanifest"
       $doc = [System.Xml.Linq.XDocument]::Load($path)
       $xName = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity"
       $doc.Root.Element($xName).Attribute("Version").Value = "$(Major).$(Minor).$(Build).0"
       $doc.Save($path)
  displayName: 'Update Version in Package.appxmanifest'

- task: MSBuild@1
  displayName: 'MSBuild boilersGraphics.Msix.wapproj'
  inputs:
    solution: 'boilersGraphics.Msix\boilersGraphics.Msix.wapproj'
    platform: 'AnyCPU'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:OutputPath=boilersGraphics /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\boilersGraphics.msix /p:AppxPackageSigningEnabled=false'
    
- task: CmdLine@2
  displayName: 'tree /F'
  inputs:
    script: 'tree /F'

- task: Windows Application Driver@0
  inputs:
    OperationType: 'Start'
    AgentResolution: '1080p'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura -- RunConfiguration.DisableAppDomain=true'
    publishTestResults: true
    projects: 'boilersGraphics.Test'

- task: Windows Application Driver@0
  condition: always()
  inputs:
    OperationType: 'Stop'

- task: reportgenerator@4
  displayName: 'コードカバレッジレポートの作成'
  inputs:
    reports: '$(System.DefaultWorkingDirectory)\boilersGraphics.Test\coverage.cobertura.xml'
    targetdir: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'
    reporttypes: 'Cobertura'

- task: PublishCodeCoverageResults@1
  displayName: 'コードカバレッジレポートの発行'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\Cobertura.xml'

# Archive files
# Compress files into .7z, .tar.gz, or .zip
- task: ArchiveFiles@2
  condition: always()
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)\boilersGraphics\bin\Release\net6.0-windows' 
    includeRootFolder: false
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/boilersGraphics_$(Major)_$(Minor)_$(Build).zip' 
    replaceExistingArchive: true 
    #verbose: # Optional
    #quiet: # Optional

# GitHub Release
# Create, edit, or delete a GitHub release
- task: GitHubRelease@0
  condition: always()
  inputs:
    gitHubConnection: dhq-boiler-azure-devops
    repositoryName: '$(Build.Repository.Name)' 
    action: 'create' # Options: create, edit, delete
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'auto' # Required when action == Create# Options: auto, manual
    #tagPattern: # Optional
    #tag: # Required when action == Edit || Action == Delete || TagSource == Manual
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: |
      '$(Build.ArtifactStagingDirectory)\boilersGraphics_$(Major)_$(Minor)_$(Build).zip'
      '$(System.DefaultWorkingDirectory)\boilersGraphics.Msix\AppPackages\boilersGraphics.Msix_**_AnyCPU.appxupload'
    assetUploadMode: 'delete' # Optional. Options: delete, replace
    isDraft: false # Optional
    isPreRelease: false # Optional
    addChangeLog: true # Optional
    compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
    #releaseTag: # Required when compareWith == LastReleaseByTag

- powershell: |
   $CI_BUILD_TAG = git describe --tags
   Write-Host "##vso[task.setvariable variable=CI_BUILD_TAG]$CI_BUILD_TAG"
  displayName: 'Set the tag name as an environment variable'

- task: CmdLine@2
  displayName: "pip install python-oauth2"
  inputs:
    script: >
      pip install twitter

# Python script
# Run a Python file or inline script
- task: PythonScript@0
  inputs:
    scriptSource: 'inline' # Options: filePath, inline
    #scriptPath: azure_devops/python_script/tweet.py # Required when scriptSource == filePath
    script: >
        from twitter import Twitter, OAuth

        access_token = '$(AccessToken)'

        access_token_secret = '$(AccessTokenSecret)'

        api_key = '$(APIKey)'

        api_secret = '$(APIKeySecret)'
        
        t = Twitter(auth = OAuth(access_token, access_token_secret, api_key, api_secret))

        text = 'https://github.com/dhq-boiler/boiler-s-Graphics/releases/tag/$(CI_BUILD_TAG)'

        statusUpdate = t.statuses.update(status=text)
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional