using boilersGraphics.Helpers.Animation.Export;
using boilersGraphics.Models.Animation;
using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using NUnit.Framework;
using System;
using System.Windows.Media;

namespace boilersGraphics.Test.Helpers.Animation.Export;

[TestFixture]
public class MauiAnimationCodeBehindBuilderTest
{
    [SetUp]
    public void SetUp()
    {
        boilersGraphics.App.IsTest = true;
    }

    private static readonly XamlExportSettings DefaultSettings = new();
    private static TimelineViewModel NewTimeline(double duration = 2.0) => new(duration, 30);

    [Test]
    public void 引数nullで_ArgumentNullException()
    {
        Assert.That(() => MauiAnimationCodeBehindBuilder.Build(null, DefaultSettings),
            Throws.TypeOf<ArgumentNullException>());
        Assert.That(() => MauiAnimationCodeBehindBuilder.Build(NewTimeline(), null),
            Throws.TypeOf<ArgumentNullException>());
    }

    [Test]
    public void 空Timelineで_クラス骨格_using_namespace_BeginStopAnimationが出力()
    {
        var cs = MauiAnimationCodeBehindBuilder.Build(NewTimeline(), DefaultSettings);
        Assert.That(cs, Does.Contain("// Generated by boilersGraphics Phase 5.5 v1.0"));
        Assert.That(cs, Does.Contain("using Microsoft.Maui.Controls;"));
        Assert.That(cs, Does.Contain("using Microsoft.Maui.Graphics;"));
        Assert.That(cs, Does.Contain("namespace MyApp.Animations;"));
        Assert.That(cs, Does.Contain("public partial class FuiAnimation : ContentView"));
        Assert.That(cs, Does.Contain("public FuiAnimation()"));
        Assert.That(cs, Does.Contain("InitializeComponent();"));
        Assert.That(cs, Does.Contain("Loaded += (s, e) => BeginAnimation();"));
        Assert.That(cs, Does.Contain("public void BeginAnimation()"));
        Assert.That(cs, Does.Contain("StopAnimation();"));
        Assert.That(cs, Does.Contain("public void StopAnimation()"));
    }

    [Test]
    public void Double系Track_AnimationAdd_と_Commitが出力()
    {
        var t = NewTimeline(2.0);
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Left.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 0.0, EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, 100.0, EasingKind.SineEase, EasingMode.EaseInOut));
        t.Tracks.Add(track);

        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        var targetName = ShapeToXamlMapper.MakeXName(rect.ID);

        Assert.That(cs, Does.Contain("var __parent_0_Left = new Animation();"));
        Assert.That(cs, Does.Contain("__parent_0_Left.Add(0, 0.5, new Animation(d => { "));
        Assert.That(cs, Does.Contain("AbsoluteLayout.GetLayoutBounds(" + targetName + ")"));
        Assert.That(cs, Does.Contain(", 0, 100, Easing.Linear));"));
        Assert.That(cs, Does.Contain("__parent_0_Left.Commit(this, \"" + targetName + "_Left_anim_0\", length: 2000u, easing: Easing.Linear, repeat: () => false);"));
        Assert.That(cs, Does.Contain("this.AbortAnimation(\"" + targetName + "_Left_anim_0\");"));
    }

    [Test]
    public void Loop_true_は_repeat_true()
    {
        var t = NewTimeline();
        t.Loop.Value = true;
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Width.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 10.0, EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, 50.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("repeat: () => true);"));
    }

    [Test]
    public void Color系Track_LerpColorヘルパーが出力()
    {
        var t = NewTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "FillBrush.Value", AnimatedValueType.Brush));
        track.Keyframes.Add(new Keyframe(0.0, new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0x00, 0x00)), EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, new SolidColorBrush(Color.FromArgb(0xFF, 0x00, 0xFF, 0x00)), EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);

        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("var c = LerpColor("));
        Assert.That(cs, Does.Contain("Color.FromArgb(\"#FFFF0000\")"));
        Assert.That(cs, Does.Contain("Color.FromArgb(\"#FF00FF00\")"));
        Assert.That(cs, Does.Contain(".Fill = new SolidColorBrush(c);"));
        Assert.That(cs, Does.Contain("private static Color LerpColor(Color from, Color to, double d)"));
    }

    [Test]
    public void Double系Trackだけなら_LerpColor出ない()
    {
        var t = NewTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Width.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 10.0, EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, 50.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Not.Contain("LerpColor"));
    }

    [Test]
    public void 未対応PropertyPathは_コメントでスキップ()
    {
        var t = NewTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "FooBar.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 1.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("// Skipped: unsupported PropertyPath 'FooBar.Value'"));
        Assert.That(cs, Does.Not.Contain("new Animation"));
    }

    [Test]
    public void Keyframeが1個以下のTrackはスキップ()
    {
        var t = NewTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Width.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 1.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("// Skipped Track 0: fewer than 2 keyframes"));
    }

    [Test]
    public void BounceEaseInOut_は_BounceHelperを末尾に追加()
    {
        var t = NewTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Left.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 0.0, EasingKind.BounceEase, EasingMode.EaseInOut));
        track.Keyframes.Add(new Keyframe(1.0, 100.0, EasingKind.BounceEase, EasingMode.EaseInOut));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("BoilersBounceOut"));
        Assert.That(cs, Does.Contain("private static double BoilersBounceOut"));
    }

    [Test]
    public void TargetNamespace_と_ClassNameが反映()
    {
        var s = DefaultSettings with { TargetNamespace = "Acme.Foo", ClassName = "Spin" };
        var cs = MauiAnimationCodeBehindBuilder.Build(NewTimeline(), s);
        Assert.That(cs, Does.Contain("namespace Acme.Foo;"));
        Assert.That(cs, Does.Contain("public partial class Spin : ContentView"));
        Assert.That(cs, Does.Contain("public Spin()"));
    }

    [Test]
    public void IncludeHeaderComment_false_でヘッダなし()
    {
        var s = DefaultSettings with { IncludeHeaderComment = false };
        var cs = MauiAnimationCodeBehindBuilder.Build(NewTimeline(), s);
        Assert.That(cs, Does.Not.Contain("Generated by"));
        Assert.That(cs, Does.StartWith("using"));
    }

    [Test]
    public void Duration0でも_lengthは1ms以上()
    {
        var t = new TimelineViewModel(0.0, 30);
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Width.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 10.0, EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(0.5, 50.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);
        var cs = MauiAnimationCodeBehindBuilder.Build(t, DefaultSettings);
        Assert.That(cs, Does.Contain("length: 1000u"));  // 0 -> 1.0s fallback
    }
}
