using boilersGraphics.Helpers.Animation.Export;
using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace boilersGraphics.Test.Helpers.Animation.Export;

[TestFixture]
public class MauiAnimationXamlBuilderTest
{
    [SetUp]
    public void SetUp()
    {
        boilersGraphics.App.IsTest = true;
    }

    private static readonly XamlExportSettings DefaultSettings = new();
    private static TimelineViewModel NewEmptyTimeline() => new(1.0, 30);
    private static IReadOnlyList<SelectableDesignerItemViewModelBase> NoItems() =>
        Array.Empty<SelectableDesignerItemViewModelBase>();

    [Test]
    public void 引数nullで_ArgumentNullException()
    {
        Assert.That(() => MauiAnimationXamlBuilder.Build(null, NoItems(), DefaultSettings),
            Throws.TypeOf<ArgumentNullException>());
        Assert.That(() => MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), null, DefaultSettings),
            Throws.TypeOf<ArgumentNullException>());
        Assert.That(() => MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), NoItems(), null),
            Throws.TypeOf<ArgumentNullException>());
    }

    [Test]
    public void 空Timelineと図形なしでも_ContentView骨格が出る()
    {
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), NoItems(), DefaultSettings);
        Assert.That(xaml, Does.StartWith("<!-- Generated by boilersGraphics Phase 5.5 v1.0 -->"));
        Assert.That(xaml, Does.Contain("<ContentView x:Class=\"MyApp.Animations.FuiAnimation\""));
        Assert.That(xaml, Does.Contain("xmlns=\"http://schemas.microsoft.com/dotnet/2021/maui\""));
        Assert.That(xaml, Does.Contain("<ContentView.Content>"));
        Assert.That(xaml, Does.Contain("<AbsoluteLayout>"));
        Assert.That(xaml, Does.Contain("</AbsoluteLayout>"));
        Assert.That(xaml, Does.Contain("</ContentView.Content>"));
        Assert.That(xaml, Does.EndWith("</ContentView>" + DefaultSettings.NewLine));
    }

    [Test]
    public void IncludeHeaderComment_false_でヘッダなし()
    {
        var s = DefaultSettings with { IncludeHeaderComment = false };
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        Assert.That(xaml, Does.Not.Contain("Generated by boilersGraphics"));
        Assert.That(xaml, Does.StartWith("<ContentView"));
    }

    [Test]
    public void TargetNamespaceとClassNameがxClassに反映()
    {
        var s = DefaultSettings with { TargetNamespace = "Acme.Foo", ClassName = "Spin" };
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        Assert.That(xaml, Does.Contain("x:Class=\"Acme.Foo.Spin\""));
    }

    [Test]
    public void 対応図形がAbsoluteLayout内に出る()
    {
        var rect = new NRectangleViewModel(10, 20, 30, 40);
        rect.EdgeBrush.Value = null;
        rect.FillBrush.Value = null;
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), new[] { rect }, DefaultSettings);
        Assert.That(xaml, Does.Contain("<Rectangle x:Name=\"" + MauiShapeToXamlMapper.MakeXName(rect.ID) + "\""));
        Assert.That(xaml, Does.Contain("AbsoluteLayout.LayoutBounds=\"10,20,30,40\""));
    }

    [Test]
    public void Path系図形_resolverなしはスキップコメント()
    {
        var poly = new NPolygonViewModel(0, 0, 10, 10);
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), new[] { poly }, DefaultSettings);
        Assert.That(xaml, Does.Contain("<!-- Skipped unsupported item: NPolygonViewModel"));
        Assert.That(xaml, Does.Not.Contain("<Polygon"));
        Assert.That(xaml, Does.Not.Contain("<Path"));
    }

    [Test]
    public void Path系図形_resolverありはPolygon要素を出力()
    {
        var poly = new NPolygonViewModel(0, 0, 100, 100);
        var fig = new System.Windows.Media.PathFigure(new System.Windows.Point(0, 0), new System.Windows.Media.PathSegment[]
        {
            new System.Windows.Media.LineSegment(new System.Windows.Point(100, 0), true),
            new System.Windows.Media.LineSegment(new System.Windows.Point(50, 100), true),
        }, closed: true);
        var g = new System.Windows.Media.PathGeometry(new[] { fig });
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), new[] { poly }, DefaultSettings, pathGeometryResolver: _ => g);
        Assert.That(xaml, Does.Contain("<Polygon x:Name=\"" + MauiShapeToXamlMapper.MakeXName(poly.ID) + "\""));
        Assert.That(xaml, Does.Contain("Points=\"0,0 100,0 50,100\""));
    }

    [Test]
    public void インデント幅2は階層幅に反映()
    {
        var s = DefaultSettings with { IndentWidth = 2 };
        var xaml = MauiAnimationXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        Assert.That(xaml, Does.Contain("\n  <ContentView.Content>"));
        Assert.That(xaml, Does.Contain("\n    <AbsoluteLayout>"));
    }
}
