using boilersGraphics.Helpers.Animation.Export;
using NUnit.Framework;

namespace boilersGraphics.Test.Helpers.Animation.Export;

[TestFixture]
public class WpfStoryboardCodeBehindBuilderTest
{
    [Test]
    public void null_settings_は_空文字()
    {
        Assert.That(WpfStoryboardCodeBehindBuilder.Build(null), Is.EqualTo(string.Empty));
    }

    [Test]
    public void デフォルト設定は_using_namespace_partial_classが出る()
    {
        var s = new XamlExportSettings();
        var cs = WpfStoryboardCodeBehindBuilder.Build(s);
        Assert.That(cs, Does.Contain("using System.Windows.Controls;"));
        Assert.That(cs, Does.Contain("using System.Windows.Media.Animation;"));
        Assert.That(cs, Does.Contain("namespace MyApp.Animations;"));
        Assert.That(cs, Does.Contain("public partial class FuiAnimation : UserControl"));
    }

    [Test]
    public void コンストラクタは_InitializeComponent_を呼ぶ()
    {
        var cs = WpfStoryboardCodeBehindBuilder.Build(new XamlExportSettings());
        Assert.That(cs, Does.Contain("public FuiAnimation()"));
        Assert.That(cs, Does.Contain("InitializeComponent();"));
    }

    [Test]
    public void BeginAnimation_StopAnimation_メソッドが出力される()
    {
        var cs = WpfStoryboardCodeBehindBuilder.Build(new XamlExportSettings());
        Assert.That(cs, Does.Contain("public void BeginAnimation()"));
        Assert.That(cs, Does.Contain("public void StopAnimation()"));
        Assert.That(cs, Does.Contain("FindResource(\"MainStoryboard\")"));
        Assert.That(cs, Does.Contain("sb.Begin(this, true);"));
        Assert.That(cs, Does.Contain("sb.Stop(this);"));
    }

    [Test]
    public void AccessModifier_internal_は反映される()
    {
        var s = new XamlExportSettings { AccessModifier = "internal" };
        var cs = WpfStoryboardCodeBehindBuilder.Build(s);
        Assert.That(cs, Does.Contain("internal partial class FuiAnimation"));
        Assert.That(cs, Does.Not.Contain("public partial class"));
    }

    [Test]
    public void TargetNamespace_と_ClassName_が反映()
    {
        var s = new XamlExportSettings { TargetNamespace = "Acme.Foo", ClassName = "Spin" };
        var cs = WpfStoryboardCodeBehindBuilder.Build(s);
        Assert.That(cs, Does.Contain("namespace Acme.Foo;"));
        Assert.That(cs, Does.Contain("public partial class Spin : UserControl"));
        Assert.That(cs, Does.Contain("public Spin()"));
    }

    [Test]
    public void IncludeHeaderComment_false_でヘッダ無し()
    {
        var s = new XamlExportSettings { IncludeHeaderComment = false };
        var cs = WpfStoryboardCodeBehindBuilder.Build(s);
        Assert.That(cs, Does.Not.Contain("Generated by"));
    }

    [Test]
    public void インデント幅2_でも_適切な階層幅()
    {
        var s = new XamlExportSettings { IndentWidth = 2, NewLine = "\n" };
        var cs = WpfStoryboardCodeBehindBuilder.Build(s);
        Assert.That(cs, Does.Contain("\n  public FuiAnimation()"));
        Assert.That(cs, Does.Contain("\n    InitializeComponent();"));
    }
}
