using boilersGraphics.Helpers.Animation.Export;
using boilersGraphics.Models.Animation;
using boilersGraphics.ViewModels;
using boilersGraphics.ViewModels.Animation;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Windows.Media;

namespace boilersGraphics.Test.Helpers.Animation.Export;

[TestFixture]
public class WpfStoryboardXamlBuilderTest
{
    [SetUp]
    public void SetUp()
    {
        boilersGraphics.App.IsTest = true;
    }

    private static readonly XamlExportSettings DefaultSettings = new();

    private static TimelineViewModel NewEmptyTimeline() => new(2.0, 30);

    private static IReadOnlyList<SelectableDesignerItemViewModelBase> NoItems() =>
        Array.Empty<SelectableDesignerItemViewModelBase>();

    [Test]
    public void 引数nullで_ArgumentNullException()
    {
        Assert.That(() => WpfStoryboardXamlBuilder.Build(null, NoItems(), DefaultSettings),
            Throws.TypeOf<ArgumentNullException>());
        Assert.That(() => WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), null, DefaultSettings),
            Throws.TypeOf<ArgumentNullException>());
        Assert.That(() => WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), null),
            Throws.TypeOf<ArgumentNullException>());
    }

    [Test]
    public void 空タイムライン_空図形でも_UserControl骨格が出力()
    {
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), DefaultSettings);

        Assert.That(xaml, Does.StartWith("<!-- Generated by boilersGraphics Phase 5.5 v1.0 -->"));
        Assert.That(xaml, Does.Contain("<UserControl x:Class=\"MyApp.Animations.FuiAnimation\""));
        Assert.That(xaml, Does.Contain("xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\""));
        Assert.That(xaml, Does.Contain("<Storyboard x:Key=\"MainStoryboard\">"));
        Assert.That(xaml, Does.Contain("</Storyboard>"));
        Assert.That(xaml, Does.Contain("<EventTrigger RoutedEvent=\"UserControl.Loaded\">"));
        Assert.That(xaml, Does.Contain("<BeginStoryboard Storyboard=\"{StaticResource MainStoryboard}\" />"));
        Assert.That(xaml, Does.Contain("<Canvas>"));
        Assert.That(xaml, Does.Contain("</Canvas>"));
        Assert.That(xaml, Does.EndWith("</UserControl>" + DefaultSettings.NewLine));
    }

    [Test]
    public void IncludeHeaderComment_false_でヘッダは出ない()
    {
        var s = DefaultSettings with { IncludeHeaderComment = false };
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        Assert.That(xaml, Does.Not.Contain("Generated by boilersGraphics"));
        Assert.That(xaml, Does.StartWith("<UserControl"));
    }

    [Test]
    public void TargetNamespace_と_ClassName_は_x_Class_に反映()
    {
        var s = DefaultSettings with { TargetNamespace = "Acme.Foo", ClassName = "Spin" };
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        Assert.That(xaml, Does.Contain("x:Class=\"Acme.Foo.Spin\""));
    }

    [Test]
    public void Loop_true_は_RepeatBehavior_Forever()
    {
        var t = NewEmptyTimeline();
        t.Loop.Value = true;
        var xaml = WpfStoryboardXamlBuilder.Build(t, NoItems(), DefaultSettings);
        Assert.That(xaml, Does.Contain("<Storyboard x:Key=\"MainStoryboard\" RepeatBehavior=\"Forever\">"));
    }

    [Test]
    public void Loop_false_は_RepeatBehavior_出ない()
    {
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), DefaultSettings);
        Assert.That(xaml, Does.Not.Contain("RepeatBehavior"));
    }

    [Test]
    public void 線形Trackは_LinearDoubleKeyFrameを並べる()
    {
        var t = NewEmptyTimeline();
        var rect = new NRectangleViewModel(0, 0, 50, 50);
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Left.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 0.0, EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, 100.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);

        var xaml = WpfStoryboardXamlBuilder.Build(t, new[] { rect }, DefaultSettings);

        Assert.That(xaml, Does.Contain("<DoubleAnimationUsingKeyFrames"));
        Assert.That(xaml, Does.Contain("Storyboard.TargetName=\"" + ShapeToXamlMapper.MakeXName(rect.ID) + "\""));
        Assert.That(xaml, Does.Contain("Storyboard.TargetProperty=\"(Canvas.Left)\""));
        Assert.That(xaml, Does.Contain("<LinearDoubleKeyFrame KeyTime=\"0:0:0\" Value=\"0\" />"));
        Assert.That(xaml, Does.Contain("<LinearDoubleKeyFrame KeyTime=\"0:0:1\" Value=\"100\" />"));
        Assert.That(xaml, Does.Not.Contain("EasingFunction"));
    }

    [Test]
    public void EasingあるTrackは_EasingKeyFrame_と_EasingFunctionブロックを出す()
    {
        var t = NewEmptyTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "Width.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 10.0, EasingKind.SineEase, EasingMode.EaseInOut));
        track.Keyframes.Add(new Keyframe(0.5, 200.0, EasingKind.SineEase, EasingMode.EaseInOut));
        t.Tracks.Add(track);

        var xaml = WpfStoryboardXamlBuilder.Build(t, new[] { rect }, DefaultSettings);

        Assert.That(xaml, Does.Contain("<EasingDoubleKeyFrame KeyTime=\"0:0:0\" Value=\"10\">"));
        Assert.That(xaml, Does.Contain("<EasingDoubleKeyFrame.EasingFunction>"));
        Assert.That(xaml, Does.Contain("<SineEase EasingMode=\"EaseInOut\" />"));
        Assert.That(xaml, Does.Contain("</EasingDoubleKeyFrame.EasingFunction>"));
        Assert.That(xaml, Does.Contain("<EasingDoubleKeyFrame KeyTime=\"0:0:0.5\" Value=\"200\">"));
    }

    [Test]
    public void 色Track_Brush_は_SolidColorBrush_Color属性()
    {
        var t = NewEmptyTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "FillBrush.Value", AnimatedValueType.Brush));
        track.Keyframes.Add(new Keyframe(0.0, new SolidColorBrush(Color.FromArgb(0xFF, 0xFF, 0x00, 0x00)), EasingKind.LinearEase, EasingMode.EaseIn));
        track.Keyframes.Add(new Keyframe(1.0, new SolidColorBrush(Color.FromArgb(0xFF, 0x00, 0xFF, 0x00)), EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);

        var xaml = WpfStoryboardXamlBuilder.Build(t, new[] { rect }, DefaultSettings);

        Assert.That(xaml, Does.Contain("<ColorAnimationUsingKeyFrames"));
        Assert.That(xaml, Does.Contain("Storyboard.TargetProperty=\"(Shape.Fill).(SolidColorBrush.Color)\""));
        Assert.That(xaml, Does.Contain("<LinearColorKeyFrame KeyTime=\"0:0:0\" Value=\"#FFFF0000\" />"));
        Assert.That(xaml, Does.Contain("<LinearColorKeyFrame KeyTime=\"0:0:1\" Value=\"#FF00FF00\" />"));
    }

    [Test]
    public void 未対応PropertyPathは_コメントでスキップ()
    {
        var t = NewEmptyTimeline();
        var rect = new NRectangleViewModel();
        var track = new AnimationTrack(new PropertyRef(rect.ID, "FooBar.Value", AnimatedValueType.Double));
        track.Keyframes.Add(new Keyframe(0.0, 1.0, EasingKind.LinearEase, EasingMode.EaseIn));
        t.Tracks.Add(track);

        var xaml = WpfStoryboardXamlBuilder.Build(t, new[] { rect }, DefaultSettings);
        Assert.That(xaml, Does.Contain("<!-- Skipped: unsupported PropertyPath 'FooBar.Value' -->"));
        Assert.That(xaml, Does.Not.Contain("KeyFrame"));
    }

    [Test]
    public void Canvas内に_対応図形が出力()
    {
        var rect = new NRectangleViewModel(10, 20, 30, 40);
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), new[] { rect }, DefaultSettings);
        Assert.That(xaml, Does.Contain("<Rectangle x:Name=\"" + ShapeToXamlMapper.MakeXName(rect.ID) + "\""));
        Assert.That(xaml, Does.Contain("Canvas.Left=\"10\""));
    }

    [Test]
    public void Path系図形_resolver無しは_スキップコメント()
    {
        var poly = new NPolygonViewModel(0, 0, 10, 10);
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), new[] { poly }, DefaultSettings);
        Assert.That(xaml, Does.Contain("<!-- Skipped unsupported item: NPolygonViewModel"));
        Assert.That(xaml, Does.Not.Contain("<Polygon"));
        Assert.That(xaml, Does.Not.Contain("<Path"));
    }

    [Test]
    public void Path系図形_resolverあり_の場合_Polygon要素を出力()
    {
        var poly = new NPolygonViewModel(0, 0, 100, 100);
        var fig = new System.Windows.Media.PathFigure(new System.Windows.Point(0, 0), new System.Windows.Media.PathSegment[]
        {
            new System.Windows.Media.LineSegment(new System.Windows.Point(100, 0), true),
            new System.Windows.Media.LineSegment(new System.Windows.Point(50, 100), true),
        }, closed: true);
        var g = new System.Windows.Media.PathGeometry(new[] { fig });

        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), new[] { poly }, DefaultSettings,
            pathGeometryResolver: _ => g);

        Assert.That(xaml, Does.Contain("<Polygon x:Name=\"" + ShapeToXamlMapper.MakeXName(poly.ID) + "\""));
        Assert.That(xaml, Does.Contain("Points=\"0,0 100,0 50,100\""));
    }

    [Test]
    public void FormatKeyTime_秒だけ()
    {
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(0.0), Is.EqualTo("0:0:0"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(0.5), Is.EqualTo("0:0:0.5"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(1.0), Is.EqualTo("0:0:1"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(59.999), Is.EqualTo("0:0:59.999"));
    }

    [Test]
    public void FormatKeyTime_分_時_を_繰上げ()
    {
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(60.0), Is.EqualTo("0:1:0"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(61.5), Is.EqualTo("0:1:1.5"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(3600.0), Is.EqualTo("1:0:0"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(3661.5), Is.EqualTo("1:1:1.5"));
    }

    [Test]
    public void FormatKeyTime_負の値は_0()
    {
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyTime(-1.0), Is.EqualTo("0:0:0"));
    }

    [Test]
    public void FormatKeyframeValue_double_は_invariant()
    {
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyframeValue(12.5, AnimatedValueType.Double), Is.EqualTo("12.5"));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyframeValue(100.0, AnimatedValueType.Double), Is.EqualTo("100"));
    }

    [Test]
    public void FormatKeyframeValue_Color_は_AARRGGBB()
    {
        var c = Color.FromArgb(0x80, 0x12, 0x34, 0x56);
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyframeValue(c, AnimatedValueType.Color), Is.EqualTo("#80123456"));
    }

    [Test]
    public void FormatKeyframeValue_SolidColorBrush_は_Color変換()
    {
        var b = new SolidColorBrush(Color.FromArgb(0xFF, 0xAB, 0xCD, 0xEF));
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyframeValue(b, AnimatedValueType.Brush), Is.EqualTo("#FFABCDEF"));
    }

    [Test]
    public void FormatKeyframeValue_null_は_空文字()
    {
        Assert.That(WpfStoryboardXamlBuilder.FormatKeyframeValue(null, AnimatedValueType.Double), Is.EqualTo(string.Empty));
    }

    [Test]
    public void インデント幅2でも_適切な階層幅で出力()
    {
        var s = DefaultSettings with { IndentWidth = 2 };
        var xaml = WpfStoryboardXamlBuilder.Build(NewEmptyTimeline(), NoItems(), s);
        // UserControl.Resources は 2 スペース、Storyboard は 4 スペース
        Assert.That(xaml, Does.Contain("\n  <UserControl.Resources>"));
        Assert.That(xaml, Does.Contain("\n    <Storyboard"));
    }
}
